services:
  - type: web
    name: quiniela-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    rootDir: backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: quiniela-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_EMAIL
        value: millan.ricardo@gmail.com
      - key: FOOTBALL_DATA_API_KEY
        value: 3cddaa716d0c469f9a6fab31f39cfdfb
      - key: GMAIL_USER
        value: millan.ricardo@gmail.com
      - key: GMAIL_APP_PASSWORD
        value: qhkqwkwcdhagbbto
      - key: CRON_SECRET
        value: quiniela2026cron

  - type: web
    name: quiniela-frontend
    runtime: static
    staticPublishPath: frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: quiniela-db
    plan: free
    databaseName: quiniela
    user: quiniela
